# Generated by Django 5.1.7 on 2025-05-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=50)),
                ('cmc_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.wallettokenbalance')),
            ],
            options={
                'unique_together': {('address', 'chain')},
            },
        ),
    ]
