# Generated by Django 5.1.7 on 2025-05-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoingeckoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=12, max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_master', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coingecko_price', to='tokens.tokenmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CoinMarketCapPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=12, max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_master', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coinmarketcap_price', to='tokens.tokenmaster')),
            ],
        ),
    ]
