# Generated by Django 5.1.7 on 2025-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
