# Generated by Django 5.1.7 on 2025-05-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_price_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='token',
            new_name='token_id',
        ),
    ]
