# Generated by Django 5.1.7 on 2025-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_coingeckoprice_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coingeckoprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=40, max_digits=60),
        ),
        migrations.AlterField(
            model_name='coinmarketcapprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=40, max_digits=60),
        ),
    ]
