# Generated by Django 5.1.7 on 2025-05-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_rename_token_price_token_id'),
        ('tokens', '0006_remove_tokenexternalid_token_token_token_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.AlterField(
            model_name='price',
            name='token_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_price', to='tokens.tokenexternalid'),
        ),
    ]
