# Generated by Django 5.1.7 on 2025-05-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_coingeckoprice_price_usd_and_more'),
        ('tokens', '0002_alter_token_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coingeckoprice',
            name='token_master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coingecko_price', to='tokens.tokenmaster'),
        ),
    ]
