# Generated by Django 5.1.7 on 2025-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_coingeckoprice_token_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coingeckoprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=50, max_digits=70),
        ),
        migrations.AlterField(
            model_name='coinmarketcapprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=50, max_digits=70),
        ),
    ]
