# Generated by Django 5.1.7 on 2025-07-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_coingeckoprice_price_usd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinMarketCapPrice',
        ),
    ]
