# Generated by Django 5.1.7 on 2025-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_delete_coinmarketcapprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coingeckoprice',
            name='percentage_24h',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
