# Generated by Django 5.1.7 on 2025-05-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('coinmarketcap_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True, max_length=512, null=True)),
                ('coingecko_rank', models.IntegerField(blank=True, null=True)),
                ('coinmarketcap_rank', models.IntegerField(blank=True, null=True)),
                ('coingecko_updated_at', models.DateTimeField(blank=True, null=True)),
                ('coinmarketcap_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=50)),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('coingecko_updated_at', models.DateTimeField(blank=True, null=True)),
                ('coinmarketcap_updated_at', models.DateTimeField(blank=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implementations', to='tokens.tokenmaster')),
            ],
            options={
                'unique_together': {('chain', 'contract_address')},
            },
        ),
    ]
