# Generated by Django 5.1.7 on 2025-05-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chain', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('symbol', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.wallettokenbalance')),
            ],
            options={
                'unique_together': {('address', 'chain')},
            },
        ),
    ]
