# Generated by Django 5.1.7 on 2025-05-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinmarketcap', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.tokenmetadata')),
            ],
            options={
                'unique_together': {('address', 'coinmarketcap')},
            },
        ),
    ]
