# Generated by Django 5.1.7 on 2025-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_tokenexternalid_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenexternalid',
            name='mapping_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tokenexternalid',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tokenexternalid',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
