# Generated by Django 5.1.7 on 2025-05-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_solanatokendecimals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solanatokendecimals',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='solanatokendecimals',
            name='jupiter_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
