# Generated by Django 5.1.7 on 2025-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_tokenexternalid_mapping_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenexternalid',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
