# Generated by Django 5.1.7 on 2025-05-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_tokenexternalid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
