# Generated by Django 5.1.7 on 2025-07-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_remove_solanatokendecimals_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='coinmarketcap_updated_at',
        ),
        migrations.RemoveField(
            model_name='tokenmaster',
            name='coinmarketcap_id',
        ),
        migrations.RemoveField(
            model_name='tokenmaster',
            name='coinmarketcap_rank',
        ),
        migrations.RemoveField(
            model_name='tokenmaster',
            name='coinmarketcap_updated_at',
        ),
    ]
