# Generated by Django 5.1.7 on 2025-05-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_alter_token_contract_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenexternalid',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='token_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='tokens.tokenexternalid'),
        ),
        migrations.AlterField(
            model_name='tokenexternalid',
            name='coinmarketcap_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
