# Generated by Django 5.1.7 on 2025-05-23 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together={('user', 'wallet')},
        ),
    ]
