# Generated by Django 5.1.7 on 2025-05-23 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettokenbalance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='wallettokenbalance',
            unique_together={('wallet', 'token')},
        ),
    ]
