# Generated by Django 5.1.7 on 2025-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
        ('tokens', '0005_remove_token_coinmarketcap_updated_at_and_more'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettokenbalance',
            index=models.Index(fields=['wallet', 'token'], name='portfolio_w_wallet__76a670_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettokenbalance',
            index=models.Index(fields=['wallet'], name='portfolio_w_wallet__625ab5_idx'),
        ),
    ]
